### ISSUE TITLE
cohere.errors.too_many_requests_error.TooManyRequestsError: status_code: 429

### ISSUE THREAD

**Issue by KlausikPL** [e-p-armstrong/verustoolkit#1]
when I use cohere api I get this error nonstop when I waited 10 hours same error here is my configuration

API:
  API_KEY: SomeApiKey
  BASE_URL: https://api.cohere.com/v1/
  LARGE_LOGICAL_MODEL: command-r-plus
  LOGICAL_MODEL: command-r-plus

**Comment by e-p-armstrong** [comment]
Reduce the concurrency limit in config.yaml
